<?php

namespace Proxies\__CG__\Kunstmaan\NodeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class NodeTranslation extends \Kunstmaan\NodeBundle\Entity\NodeTranslation implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'node', 'lang', 'online', 'title', 'slug', 'url', 'publicNodeVersion', 'nodeVersions', 'weight', 'created', 'updated', 'id'];
        }

        return ['__isInitialized__', 'node', 'lang', 'online', 'title', 'slug', 'url', 'publicNodeVersion', 'nodeVersions', 'weight', 'created', 'updated', 'id'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (NodeTranslation $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setNode($node)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNode', [$node]);

        return parent::setNode($node);
    }

    /**
     * {@inheritDoc}
     */
    public function getNode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNode', []);

        return parent::getNode();
    }

    /**
     * {@inheritDoc}
     */
    public function setLang($lang)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLang', [$lang]);

        return parent::setLang($lang);
    }

    /**
     * {@inheritDoc}
     */
    public function getLang()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLang', []);

        return parent::getLang();
    }

    /**
     * {@inheritDoc}
     */
    public function isOnline()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isOnline', []);

        return parent::isOnline();
    }

    /**
     * {@inheritDoc}
     */
    public function setOnline($online)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOnline', [$online]);

        return parent::setOnline($online);
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle($title)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$title]);

        return parent::setTitle($title);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setSlug($slug)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSlug', [$slug]);

        return parent::setSlug($slug);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullSlug', []);

        return parent::getFullSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlugPart()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlugPart', []);

        return parent::getSlugPart();
    }

    /**
     * {@inheritDoc}
     */
    public function getSlug()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSlug', []);

        return parent::getSlug();
    }

    /**
     * {@inheritDoc}
     */
    public function setPublicNodeVersion(\Kunstmaan\NodeBundle\Entity\NodeVersion $publicNodeVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPublicNodeVersion', [$publicNodeVersion]);

        return parent::setPublicNodeVersion($publicNodeVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getPublicNodeVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPublicNodeVersion', []);

        return parent::getPublicNodeVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function getDraftNodeVersion()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDraftNodeVersion', []);

        return parent::getDraftNodeVersion();
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeVersions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNodeVersions', []);

        return parent::getNodeVersions();
    }

    /**
     * {@inheritDoc}
     */
    public function setNodeVersions(\Doctrine\Common\Collections\ArrayCollection $nodeVersions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNodeVersions', [$nodeVersions]);

        return parent::setNodeVersions($nodeVersions);
    }

    /**
     * {@inheritDoc}
     */
    public function getNodeVersion($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNodeVersion', [$type]);

        return parent::getNodeVersion($type);
    }

    /**
     * {@inheritDoc}
     */
    public function addNodeVersion(\Kunstmaan\NodeBundle\Entity\NodeVersion $nodeVersion)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNodeVersion', [$nodeVersion]);

        return parent::addNodeVersion($nodeVersion);
    }

    /**
     * {@inheritDoc}
     */
    public function getDefaultAdminType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDefaultAdminType', []);

        return parent::getDefaultAdminType();
    }

    /**
     * {@inheritDoc}
     */
    public function getRef(\Doctrine\ORM\EntityManager $em, $type = 'public')
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRef', [$em, $type]);

        return parent::getRef($em, $type);
    }

    /**
     * {@inheritDoc}
     */
    public function setUrl($url)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrl', [$url]);

        return parent::setUrl($url);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrl()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrl', []);

        return parent::getUrl();
    }

    /**
     * {@inheritDoc}
     */
    public function setWeight($weight)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setWeight', [$weight]);

        return parent::setWeight($weight);
    }

    /**
     * {@inheritDoc}
     */
    public function getWeight()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getWeight', []);

        return parent::getWeight();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreated', []);

        return parent::getCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreated($created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreated', [$created]);

        return parent::setCreated($created);
    }

    /**
     * {@inheritDoc}
     */
    public function getUpdated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUpdated', []);

        return parent::getUpdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setUpdated($updated)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUpdated', [$updated]);

        return parent::setUpdated($updated);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', [$id]);

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

}
