<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXzOVlxQ\srcApp_KernelDevContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXzOVlxQ/srcApp_KernelDevContainer.php') {
    touch(__DIR__.'/ContainerXzOVlxQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevContainer::class, false)) {
    \class_alias(\ContainerXzOVlxQ\srcApp_KernelDevContainer::class, srcApp_KernelDevContainer::class, false);
}

return new \ContainerXzOVlxQ\srcApp_KernelDevContainer([
    'container.build_hash' => 'XzOVlxQ',
    'container.build_id' => '71c9ab5b',
    'container.build_time' => 1625552900,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXzOVlxQ');
