<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUlHNNJ2\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUlHNNJ2/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUlHNNJ2.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUlHNNJ2\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUlHNNJ2\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UlHNNJ2',
    'container.build_id' => '053c2bb3',
    'container.build_time' => 1626765951,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUlHNNJ2');
