<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSavVpJQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSavVpJQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSavVpJQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSavVpJQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerSavVpJQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'SavVpJQ',
    'container.build_id' => 'ec2a9945',
    'container.build_time' => 1626766063,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSavVpJQ');
